spring:
  redis:
    host: localhost
    port: 6379
    password: ""
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 10000ms
  datasource:
    url: jdbc:postgresql://localhost:32769/workforge
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: DEBUG
bucket4j:
  limits:
    - capacity: 10
      refillTokens: 10
      refillInterval: 1m
      timeout: 500ms
